# Generated by Django 5.1.3 on 2024-11-19 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_transaction_edited_by_transaction_edited_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
