# Generated by Django 5.1.3 on 2024-11-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transaction_is_credit_transaction_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_credit',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
